---    
  - name: development environment installed
    apt:
      name: build-essential
      state: latest

  - name: Create /etc/motd file
    copy:
      dest: "/etc/motd"
      content: |
        ######################################
        # Instance Type: <%=instance.instanceTypeName%>    #
        # OS:            <%=server.osType%>    #
        # This came from Ansible playbook!     #
        ######################################
